s

diff --git a/PHILOS/MYPHILOS/philo/Makefile b/PHILOS/MYPHILOS/philo/Makefile
--- a/PHILOS/MYPHILOS/philo/Makefile
+++ b/PHILOS/MYPHILOS/philo/Makefile
@@ -15,9 +15,9 @@ SRCFILES	:= main.c init.c threads.c philo_observer.c actions.c utils.c
 SRC			:= $(addprefix ./src/, $(SRCFILES))
 OBJ			:= $(SRC:.c=.o)  # Convierte los archivos fuente .c a archivos objeto .o
 
-CC			:= gcc
-CFLAGS		:= -Wall -Wextra -Werror -lpthread
-# SANITIZER	:= -fsanitize=thread
+CC			:= cc
+CFLAGS		:= -Wall -Wextra -Werror -pthread
+SANITIZER	:= -fsanitize=thread -g
 
 $(NAME): $(OBJ)
 	$(CC) $(CFLAGS) $(OBJ) -o $(NAME) $(SANITIZER)
@@ -39,7 +39,41 @@ re: fclean all
 debug: CFLAGS += -g
 debug: re	
 
+test: $(NAME)
+	@echo "Running tests..."
+	@correct=0; \
+	incorrect=0; \
+	failed_tests=""; \
+	num=20; \
+	trap 'echo "Tests interrupted"; kill $$!; exit 1' INT; \
+	for args in "4 410 200 200" "5 800 200 200" "5 600 150 150" "100 800 200 200" "105 800 200 200" "200 800 200 200"; do \
+		echo "[+] Running with parameters: $$args"; \
+		sleep 3; \
+		./$(NAME) $$args > /dev/null 2>&1 & pid=$$!; \
+		sleep $$num; \
+		if ps -p $$pid > /dev/null; then \
+			echo "Done: Execution of './$(NAME) $$args' ran for $$num seconds successfully."; \
+			kill $$pid; \
+			num=$$((num)); \
+			wait $$pid 2>/dev/null; \
+			correct=$$((correct + 1)); \
+		else \
+			echo "Error: Execution of './$(NAME) $$args' finished before $$num seconds."; \
+			incorrect=$$((incorrect + 1)); \
+			failed_tests="$$failed_tests $$args"; \
+			# break; \
+		fi; \
+		sleep 2; \
+	done; \
+	echo "=============================="; \
+	echo "Test Results:"; \
+	echo "Correct Tests: $$correct"; \
+	echo "Incorrect Tests: $$incorrect"; \
+	echo "Failed Tests: $$failed_tests"; \
+	echo "=============================="
+
+
 delay:
 	@python3 delay_o_meter.py
 
-.PHONY: all clean fclean re debug delay
+.PHONY: all clean fclean re debug test delay
